### ISSUE TITLE
https://prometheaninfosec.com/neoadhd repo is down

### ISSUE THREAD

**Issue by ethack** [adhdproject/buildkit#5]
Had someone contact me with this issue.  The install script references https://prometheaninfosec.com/neoadhd but that URL returns a 403 Forbidden response.

**Comment by PrometheanInfoSec** [comment]
When did they contact you?

I got an email about this right after I made the last update.  The update messed with the repo.

That's already handled.  

The repo doesn't allow directory listings.  Try this: https://prometheaninfosec.com/neoadhd/Packages

I'll go run an install and search for any issues.  Was planning on working on ADHD today anyway so this is perfect.  I can give directory listing permissions to that one folder.

**Comment by ethack** [comment]
Awesome, thank you for the quick response!  The email was actually 7 days ago and I just found that that mailing list wasn't making it to my inbox.  They actually reported the script showed a 404 and not 403.  The 403 is what I saw just now, but your response explains why perfectly.  Sounds like you've addressed the issue and I'm way behind haha.

**Comment by PrometheanInfoSec** [comment]
I'm always by my phone, I had this problem patched within 23 minutes of having received the email.

Directory listings are allowed in the repo now.

I can handle patches and updates really quickly.  I just need prompting.
